GET  http://localhost:3000/users HTTP/1.1

###

POST  http://localhost:3000/users HTTP/1.1
content-type: application/json

{"name": "Hasan Kalemdaroğlu", "handle": "@hasankalemdar", "email": "hasankalemdar@twitter.com"}

###

DELETE  http://localhost:3000/users/611390360384a2befbbc7466 HTTP/1.1

###

GET http://localhost:3000/users/6113b3d9e2c6234211727249

###

POST    http://localhost:3000/users/6113dc40306ad96bcd30b253/tweets HTTP/1.1
content-type: application/json

{"body": "#gülegüle"}

###

PATCH   http://localhost:3000/users/6113a464e332bd183bf840d2 HTTP/1.1
content-type: application/json

{"name": "Cihat"}

###

PATCH   http://localhost:3000/users/6113dc5e306ad96bcd30b255/following HTTP/1.1
content-type: application/json

{"userToFollowId": "6113dc26306ad96bcd30b251"}

###

PATCH   http://localhost:3000/users/6113dc40306ad96bcd30b253/like HTTP/1.1
content-type: application/json

{"likeTweetId": "6113dcaf306ad96bcd30b26c"}

###

PATCH   http://localhost:3000/users/6113dc26306ad96bcd30b251/retweet HTTP/1.1
content-type: application/json

{"retweetId": "6113dcaf306ad96bcd30b26c"}