@startuml "Class Diagram"

Title: Twitter Clone

class User {
  name: string
  handle: string
  email: string

  profilePicture: string
  bio: string
  location: string
  website: string
  createdAt: Date
  dateOfBirth: Date

  followers: [User]
  following: [User]
  likedTweet: [Tweet]
  
  follow(user: User)
  tweet(tweet: Tweet)
  like(tweet: Tweet)
  retweet(tweet: Tweet)
}

class Tweet {
  author: User
  body: string
  
  createdAt: Date
  originalTweet: Tweet

  likes: [User]
  replies: [Tweet]
  retweets: [Tweet]
  attachments: []
}

@enduml